addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: ruby

services:
  - docker

rvm:
  - ruby-head
  - 2.6
  - 2.5

install:
  - bundle install --without development
  - docker run -itd -p 80:80 --name documentserver onlyoffice/documentserver-ie:latest
  - sleep 60
  - docker exec -it documentserver supervisorctl start all

script:
  - bundle exec rake spec
