language: ruby

services:
  - docker

rvm:
#  - ruby-head
  - 2.5.1
#  - 2.4.4
#  - 2.3.7
#  - 2.2.10
#  - 2.1.10

before_install:
  - gem update --system
install:
  - bundle install --without development
  - docker run -itd -p 80:80 --name documentserver onlyoffice/documentserver-ie:latest
  - sleep 60
  - docker exec -it documentserver supervisorctl start all
  - rspec spec
