require_relative 'onlyoffice_documentserver_testing_framework/loader'
require_relative 'onlyoffice_documentserver_testing_framework/test_instance_docs'
require_relative 'onlyoffice_documentserver_testing_framework/version'
