name: Ruby
on: [push]
jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]
    continue-on-error: ${{ matrix.allow-failures }}
    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']
        allow-failures: [false]
        include:
          - ruby: head
            allow-failures: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install ruby dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Check source files using `rubocop`
        run: rubocop
      - name: Check that code 100% documented
        run: yardoc . | grep -q '100.00% documented'
      - name: Run DocumentServer
        run: |
          docker run -id -p 80:80 --name documentserver onlyoffice/documentserver-ee:latest
          sleep 120
          docker exec -i documentserver supervisorctl start all
      - name: Update to current stable google-chrome
        run: |
         echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
         sudo apt-get -y update
         sudo apt-get -y install google-chrome-stable
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake spec
      - uses: codecov/codecov-action@v4
        if: matrix.ruby == '3.3'
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
