name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, head]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run DocumentServer
      run: |
        docker run -id -p 80:80 --name documentserver onlyoffice/documentserver-ie:latest
        sleep 60
        docker exec -i documentserver supervisorctl start all
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake spec
    - uses: actions/setup-node@v1
    - name: Check markdown files using `markdownlint`
      run: |
        npm install -g markdownlint-cli
        markdownlint *.md
    - name: Check that code 100% documented
      run: yardoc . | grep -q '100.00% documented'